# Copyright 2025-present DatusAI, Inc.
# Licensed under the Apache License, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for details.

"""Schemas for the ``analysis/`` directory shared by the report and dashboard
subagents.

The visual report / dashboard artifacts grow an ``analysis/`` subdirectory
alongside ``queries/`` and ``render/``:

* ``analysis/intent.md`` — raw user prompts, append-only. Plain markdown,
  no Pydantic model — just a list of timestamped sections, each wrapping
  the prompt in a fenced code block (fence length adapts to content so
  prompts containing ```` ``` ```` are still preserved losslessly).
  Filtered at write time to drop renderer error reports and
  "continue / proceed" placeholders that aren't real intent.
* ``analysis/insights.json`` — ``List[Insight]``. Confirmed findings.
  **Report only.** Dashboard data is materialized at runtime, so there
  are no pre-baked conclusions to surface.
* ``analysis/suggested_questions.json`` — ``List[SuggestedQuestion]``.
  Exactly 5 follow-up questions. Both kinds. Surfaced via the detail
  API as UI chips — NOT preloaded into the ask-* agent prompt (to
  avoid anchoring on a fixed question set when the user types an
  open-ended follow-up).
* ``analysis/subject_refs.json`` — :class:`SubjectRefs`. Snapshot of
  every subject-library asset (metric / reference_sql)
  any ``queries/<name>.brief.json`` declared in its ``uses`` block.
  Generated by code, not by the LLM (the LLM declares ``uses`` at
  ``save_query`` time when it's most knowledgeable; code aggregates).
  **Present-iff-non-empty**: when no query declared any subject-library
  asset, no file is written — an absent file means "no subject-library
  attribution" rather than "empty / unknown".
* ``queries/<name>.brief.json`` — :class:`QueryBrief`. Per-query
  metadata (hypothesis / uses / caveats) written by the LLM the
  moment it calls ``save_query`` / ``save_query_template``. Earlier
  iterations also stored ``goal`` / ``datasource`` / ``created_at``;
  those were dropped because ``goal`` duplicates the SQL header
  comment, ``datasource`` lives in the result JSON, and ``created_at``
  is recoverable from file mtime. Hypothesis + caveats are the
  fields a follow-up consultant actually needs.

Cross-file references are strictly one-directional from fine-grained
objects to coarse ones (or to subject-library ids) — see
``docs/analysis_artifacts.md`` for the full reference graph and the
rationale for not storing reverse indexes.
"""

from __future__ import annotations

import re
from typing import List, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field, model_validator

# Same character set as ``REPORT_SLUG_RE`` / ``QUERY_SLUG_RE`` so insight
# ids stay filesystem-friendly and easy to ``grep`` from compiled HTML
# output. Length cap matches QUERY_SLUG_RE; insight slugs are LLM-chosen
# identifiers, not paths.
ANALYSIS_SLUG_PATTERN = r"^[a-z0-9_]{1,64}$"
ANALYSIS_SLUG_RE = re.compile(ANALYSIS_SLUG_PATTERN)

SubjectAssetKind = Literal["metric", "reference_sql"]

SuggestionKind = Literal["quick", "deep_dive"]


class SubjectAssetRef(BaseModel):
    """One subject-library reference identified by its natural key.

    A subject-library asset (metric / reference_sql) is
    uniquely addressed by the subject-tree ``path`` plus the leaf
    ``name`` — the same two values every discovery tool
    (``list_metrics``, ``search_metrics``, ``list_subject_tree``)
    surfaces back to the LLM, and the same two values the ``ask_*``
    consultant needs to call ``get_metrics(path, name)`` /
    ``get_reference_sql(path, name)`` for the full definition.

    Opaque storage-layer ids (``metric:Foo/Bar.baz``) are deliberately
    NOT part of this wire contract — they leak storage concerns into
    the LLM workflow and historically drove LLMs to invent malformed
    strings (see PR follow-up notes). Dedup happens on
    ``(tuple(path), name)``.
    """

    model_config = ConfigDict(extra="forbid")

    path: List[str] = Field(
        ...,
        min_length=1,
        description=(
            "Subject-tree path to the asset, e.g. ``['Commerce', 'Orders', "
            "'Average_Order_Value']``. Each element must be non-empty. The "
            "path is the same list every discovery tool already returns; "
            "copy it verbatim instead of joining into a string."
        ),
    )
    name: str = Field(
        ...,
        min_length=1,
        description=(
            "Leaf name of the asset, e.g. ``'average_gross_order_value'``. "
            "Combined with ``path``, this is the natural key the "
            "subject-library uses for retrieval."
        ),
    )


class SubjectRefs(BaseModel):
    """Subject-library attribution payload — shared shape for both
    ``QueryBrief.uses`` (the per-query declaration written by the LLM
    at ``save_query`` time) and ``analysis/subject_refs.json`` (the
    code-aggregated, deduped index written at finalize time).

    Buckets matching the asset kinds Datus' subject library
    exposes today; future kinds can be added without breaking older
    reasoning files because each bucket defaults to an empty list.
    """

    model_config = ConfigDict(extra="forbid")

    metrics: List[SubjectAssetRef] = Field(
        default_factory=list,
        description="Metrics (semantic-model entries) that informed this query's design.",
    )
    reference_sql: List[SubjectAssetRef] = Field(
        default_factory=list,
        description="Reference-SQL entries the query borrows shape / patterns from.",
    )


class QueryBrief(BaseModel):
    """Schema for ``queries/<name>.brief.json`` — the per-query "why we
    wrote this" sidecar.

    Sits next to ``<name>.sql`` / ``<name>.json`` (report) or
    ``<name>.sql.j2`` / ``<name>.params.json`` (dashboard) — three- or
    four-file query bundles depending on artifact kind. Written atomically
    by ``save_query`` / ``save_query_template`` in the same call that
    persists the SQL itself, so a query bundle is always complete or
    completely absent.

    Trimmed to the three fields a follow-up consultant actually needs:

    * ``hypothesis`` — what the LLM expected to see when it wrote the
      query. Lets the consultant explain "this query was looking for X"
      without inventing motivation.
    * ``uses`` — subject-library asset attribution. Powers
      ``analysis/subject_refs.json`` aggregation and lets the consultant
      know which curated metrics / reference SQL to cite
      when answering related follow-ups.
    * ``caveats`` — non-obvious choices a future reader would miss
      (non-standard join, outlier filter, weighted avg, sample
      restriction). The system prompt explicitly tells the LLM to leave
      this empty for routine queries.

    ``goal`` was removed because it duplicates the SQL header comment.
    ``datasource`` and ``created_at`` were removed because the matching
    ``<name>.json`` (or ``<name>.params.json``) already carries them.

    Write-once-overwrite (no append): rerunning a same-named query
    replaces this file alongside its SQL and JSON files. History lives
    in git, not inside the file.
    """

    model_config = ConfigDict(extra="forbid")

    name: str = Field(
        ...,
        pattern=ANALYSIS_SLUG_PATTERN,
        description="Query slug, matches the sibling ``<name>.sql`` filename.",
    )
    hypothesis: str = Field(
        ...,
        min_length=1,
        max_length=500,
        description=(
            "One-sentence concrete prediction the LLM expects this query to "
            "validate or refute (e.g. 'high-risk signups cluster around "
            "promotional campaigns'). Empty / placeholder text is rejected "
            "to keep the field substantive — the system prompt instructs the "
            "LLM to skip the query rather than write filler here."
        ),
    )
    uses: SubjectRefs = Field(
        default_factory=SubjectRefs,
        description="Subject-library assets this query draws on (three buckets).",
    )
    caveats: str = Field(
        default="",
        max_length=500,
        description=(
            "Non-obvious choices a follow-up reader would otherwise miss. "
            "The system prompt sends the LLM through a five-point "
            "checklist (JOIN-type implications / hardcoded value lists / "
            "implicit filters / NULL handling / non-standard aggregation) "
            "before deciding this field is empty. Filler text like 'no "
            "caveats' is rejected at the prompt level; truly routine "
            "aggregates get an empty string."
        ),
    )


class Insight(BaseModel):
    """One confirmed finding.

    Used in ``List[Insight]`` for ``analysis/insights.json``. **Report
    only**: dashboard queries are runtime-rendered templates, so there
    are no statically-known conclusions to encode here.

    Insights cite queries (``evidence_queries``) and may cite ext-knowledge
    entries (``informed_by_knowledge``) but never cite intent.md (which
    has no stable anchor ids — see docs §6).
    """

    model_config = ConfigDict(extra="forbid")

    id: str = Field(
        ...,
        pattern=ANALYSIS_SLUG_PATTERN,
        description="LLM-chosen semantic slug; referenced by ``SuggestedQuestion.related_insight``.",
    )
    title: str = Field(..., min_length=1, max_length=200)
    summary: str = Field(..., min_length=1, max_length=1000, description="1–3 sentences stating the finding plainly.")
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="LLM-estimated confidence in [0,1]. Frontend uses it for ranking; subagent uses it as a hedging signal when answering follow-ups.",
    )
    evidence_queries: List[str] = Field(
        ...,
        min_length=1,
        description="Query slugs (matching ``queries/<name>.*`` filenames) that back this finding.",
    )
    informed_by_knowledge: List[str] = Field(
        default_factory=list,
        description="Optional ext-knowledge entry ids that shaped this insight.",
    )


class SuggestedQuestion(BaseModel):
    """One follow-up suggestion shown to the user as a quick-action chip.

    Used in ``List[SuggestedQuestion]`` for
    ``analysis/suggested_questions.json``. Both report and dashboard
    produce these — dashboards just keep ``related_insight=None``
    (there are no insights to anchor to).

    Each suggestion declares a ``kind`` so the UI can set user
    expectations on latency:

    * ``"quick"`` — answer is fully derivable from what the artifact
      already pre-loaded into the ask-agent prompt
      (``insights[]`` + per-query ``brief.json`` + preview rows + key
      tables schema). A user clicking the chip should get an answer
      with ~0 new tool calls. **Must** cite at least one
      ``related_queries`` slug or one ``related_insight`` so the
      consultant has an explicit grounding pointer.
    * ``"deep_dive"`` — legitimately requires new SQL, new tables, or
      decomposition the artifact didn't pre-compute (e.g. "why does
      Philly's AOV beat Brooklyn's" needs item-level / product-mix
      data that the headline AOV-by-store query doesn't have). UI
      surfaces a chip badge so users know ~5–10 tool calls are
      expected. ``related_queries`` / ``related_insight`` are
      optional starting hints.

    The split matters because the artifact-inlining work in the
    ask-agent prompt (insights / subject scope / query catalog /
    key-table schemas) only pays off when suggested chips actually
    point at questions the inlined context can answer. Without the
    tag, the LLM tended to emit aspirational "why" questions that
    triggered a full new analysis loop on every click — defeating the
    inlining contract.
    """

    model_config = ConfigDict(extra="forbid")

    question: str = Field(
        ...,
        min_length=1,
        max_length=300,
        description="Single-sentence follow-up. Same language as the user's prompts where possible.",
    )
    kind: SuggestionKind = Field(
        ...,
        description=(
            "``'quick'`` if the answer is fully derivable from the inlined "
            "artifact context (insights / briefs / preview rows / key-table "
            "schemas); ``'deep_dive'`` if it requires new SQL or tables the "
            "artifact didn't pre-compute. Frontend renders this as a chip tag "
            "to set latency expectations."
        ),
    )
    related_queries: List[str] = Field(
        default_factory=list,
        description=(
            "Query slugs the suggestion would build on. **Required** (non-empty "
            "or paired with ``related_insight``) when ``kind='quick'`` — the "
            "consultant needs an explicit grounding pointer to answer from the "
            "inlined preview rows."
        ),
    )
    related_insight: Optional[str] = Field(
        default=None,
        description=(
            "Insight slug this follow-up extends. Report-only; dashboards always set "
            "this to ``None`` since there are no insights for them. Counts as "
            "grounding for ``kind='quick'`` when ``related_queries`` is empty."
        ),
    )
    priority: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="LLM-assigned priority in [0,1]; frontend uses it for display order when more than one suggestion competes for the same slot.",
    )

    @model_validator(mode="after")
    def _quick_requires_grounding(self) -> "SuggestedQuestion":
        """``kind='quick'`` must declare at least one grounding pointer.

        Quick questions promise an answer with no new tool calls. The
        ask-agent only achieves that when it can cite a specific
        inlined source (``related_queries`` slug → preview rows / SQL;
        ``related_insight`` → insights.json entry). A quick question
        with no grounding either becomes a hallucinated answer or
        forces the LLM to fall back to ``glob`` / ``read_file``,
        defeating the whole point of the chip.

        ``deep_dive`` is exempt because by definition the data isn't
        in the artifact yet — pointing at a "closest existing query"
        is encouraged but not required.
        """
        if self.kind == "quick" and not self.related_queries and self.related_insight is None:
            raise ValueError(
                "SuggestedQuestion with kind='quick' must cite at least one "
                "related_queries slug or one related_insight so the consultant "
                "can answer from the inlined artifact. Use kind='deep_dive' for "
                "questions that legitimately require new SQL or tables."
            )
        return self


class FinalizeAnalysisOutput(BaseModel):
    """The schema the finalize-stage LLM call must produce in a single shot.

    Aggregates the two LLM-authored analysis files (``insights`` and
    ``suggested_questions``). ``subject_refs`` is built by code
    afterwards, so it's NOT part of this schema — keeping LLM output
    narrow makes structured-output mode more reliable.

    Dashboards set ``insights=[]`` because their data is runtime-only
    (see docs §3.5). The finalize prompt makes that explicit and the
    node-level validation enforces it for dashboard runs.

    Note: the earlier ``interpretation`` field was removed because it
    duplicated ``manifest.description`` (artifact-level framing) and was
    fully covered by ``insights[].evidence_queries`` (per-finding
    references). The follow-up consultant reads the manifest and the
    insights directly instead. ``intent.md`` curation is handled by a
    separate, dedicated LLM call (``run_intent_curation`` in
    ``datus.agent.node.visual_artifact._visual_artifact_finalize``) that
    returns a fresh markdown body
    via ``LLMBaseModel.generate`` — keeping it out of this schema
    avoids mixing transient curation signals with the persisted
    finalize products.
    """

    model_config = ConfigDict(extra="forbid")

    insights: List[Insight] = Field(
        default_factory=list,
        description="Empty for dashboard artifacts; 3–8 entries typical for reports.",
    )
    suggested_questions: List[SuggestedQuestion] = Field(
        ...,
        min_length=1,
        max_length=8,
        description="Target is exactly 5. We allow 1–8 so a marginal LLM run isn't rejected outright.",
    )
