name: "Code Quality"

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
  merge_group:

concurrency:
  group: code-quality-${{ github.event.pull_request.number || github.event.merge_group.head_sha || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  format-check:
    if: ${{ github.event_name == 'merge_group' || (!startsWith(github.event.pull_request.title, '[Doc]') && !startsWith(github.event.pull_request.title, '[doc]')) }}
    uses: ./.github/workflows/python-format-check.yml

  run-coverage:
    needs: format-check
    if: ${{ github.event_name == 'merge_group' || (!startsWith(github.event.pull_request.title, '[Doc]') && !startsWith(github.event.pull_request.title, '[doc]')) }}
    uses: ./.github/workflows/run-ut-and-coverage.yml
